import os
import re
from datetime import datetime

from .daemon import build_flag_for
from .logger import LOG, fail

_HEADER = '''\
# The MIT License (MIT)
#
# Copyright (c) {year} {copyright_holders}
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Generated by ``bornal`

    target: {daemon} on regtest.

Build the daemon and run this test with the bornal's ``pytest`` plugin::

    pytest {build_flag} latest {run_flags}tests/integration/{filename}
"""
'''

# Default body: start a regtest node and assert a clean chain.
_TEST_BODY = '''\
def {func}(node):
    """Start a regtest node and assert a clean chain."""
    cli = node("{daemon}").cli
    assert cli.get_blockchain_info()["chain"] == "regtest"
    assert cli.get_block_count() == 0
'''

_WALLET_BODY = '''\
from bornal.testing import assert_wallet_roundtrip


def {func}(node):
    """Mine to a fresh wallet and assert the matured balance + UTXOs."""
    # on-demand mining works on regtest only
    assert_wallet_roundtrip(node("{daemon}"))
'''

TEMPLATES = {
    "chain-check": {"body": _TEST_BODY, "run_flags": ""},
    "wallet-roundtrip": {"body": _WALLET_BODY, "run_flags": "--wallet "},
}

DEFAULT_TEMPLATE = "chain-check"


def _render(daemon_name, func, filename, template, copyright_holders):
    tpl = TEMPLATES[template]
    header = _HEADER.format(
        year=datetime.now().year,
        copyright_holders=copyright_holders,
        daemon=daemon_name,
        build_flag=build_flag_for(daemon_name),
        filename=filename,
        run_flags=tpl["run_flags"],
    )
    body = tpl["body"].format(func=func, daemon=daemon_name)
    return header + "\n" + body


def scaffold(
    paths,
    *,
    daemon="bitcoin-core",
    feature=None,
    template=DEFAULT_TEMPLATE,
    copyright_holders="selfcustody",
    force=False,
):
    """Write an example integration test into ``<project>/tests/integration``"""
    if template not in TEMPLATES:
        fail(
            "unknown template '%s' — known: %s",
            template,
            ", ".join(sorted(TEMPLATES)),
        )
    feature = re.sub(r"\W+", "_", feature or daemon).strip("_")
    if not feature:
        fail("invalid feature name — use letters, digits or underscores")
    func = "test_%s" % feature
    filename = "test_%s.py" % feature

    os.makedirs(paths.integration_dir, exist_ok=True)
    dest = os.path.join(paths.integration_dir, filename)
    if os.path.exists(dest) and not force:
        fail("%s already exists — use --force to overwrite", dest)

    with open(dest, "w") as handle:
        handle.write(_render(daemon, func, filename, template, copyright_holders))
    LOG.info("scaffolded %s", dest)
    return dest
