import os
import re
from datetime import datetime

from .daemon import build_flag_for
from .logger import LOG, fail

__all__ = ("DEFAULT_TEMPLATE", "TEMPLATES", "scaffold")

_HEADER = '''\
# The MIT License (MIT)
#
# Copyright (c) {year} {copyright_holders}
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Generated by ``bornal`

    target: {daemons} on regtest.

Build the daemon(s) and run this test with the bornal's ``pytest`` plugin::

    pytest {build_flags} {run_flags}tests/integration/{filename}
"""
'''

_CONFTEST_CORE = """\
import pytest

from bornal.daemon import free_port
from bornal.node import IntegrationTest


class BaseTest(IntegrationTest):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.state: dict = {}

    def set_test_params(self):
        self.add_backend("bitcoin-core", p2p_port=free_port())
        self.add_backend("bitcoin-core", p2p_port=free_port())

    def run_test(self):
        self.log.info("Tests running")

    def on_stop_test(self):
        self.log.info("Tests stopped")


@pytest.fixture(scope="module")
def test_factory(request):
    return BaseTest


@pytest.fixture
def alice(integration_test):
    return integration_test.backends[0]


@pytest.fixture
def bob(integration_test):
    return integration_test.backends[1]


@pytest.fixture
def state(integration_test):
    return integration_test.state
"""

_CONFTEST_ELECTRS = """\
import pytest

from bornal.daemon import free_port
from bornal.node import IntegrationTest


class BaseTest(IntegrationTest):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.state: dict = {}

    def set_test_params(self):
        self.add_backend("bitcoin-core", p2p_port=free_port())
        self.add_backend("electrs")

    def run_test(self):
        self.log.info("Tests running")

    def on_stop_test(self):
        self.log.info("Tests stopped")


@pytest.fixture(scope="module")
def test_factory(request):
    return BaseTest


@pytest.fixture
def alice(integration_test):
    return integration_test.backends[0]


@pytest.fixture
def electrs(integration_test):
    return integration_test.backends[1]


@pytest.fixture
def state(integration_test):
    return integration_test.state
"""

_CHAIN_BODY = """\
from bornal.testing import (
    assert_block_count,
    assert_chain,
    connect_p2p,
)


def test_000_connect(alice, bob):
    connect_p2p(alice, bob)
    assert_chain(alice, "regtest")
    assert_chain(bob, "regtest")
    assert_block_count(alice, 0)
    assert_block_count(bob, 0)
"""

_WALLET_BODY = """\
from bornal.testing import (
    COINBASE_MATURITY,
    assert_block_count,
    assert_chain,
    assert_wallet_roundtrip,
    connect_p2p,
    sync_blocks,
)


def test_000_wallet_roundtrip(alice, bob):
    connect_p2p(alice, bob)
    assert_chain(alice, "regtest")
    assert_chain(bob, "regtest")
    assert_wallet_roundtrip(alice)
    sync_blocks(alice, bob)
    assert_block_count(bob, COINBASE_MATURITY + 1)
"""

_ELECTRS_BODY = """\
from bornal.plugins.bitcoind import UNSPENDABLE_ADDRESS
from bornal.testing import (
    COINBASE_MATURITY,
    assert_block_count,
    assert_chain,
    assert_electrs_tip,
    generate_to_address,
)


def test_000_index(alice, electrs):
    assert_chain(alice, "regtest")
    assert_block_count(alice, 0)
    assert_electrs_tip(electrs, 0)
    generate_to_address(alice, UNSPENDABLE_ADDRESS, COINBASE_MATURITY + 1)
    assert_block_count(alice, COINBASE_MATURITY + 1)
    assert_electrs_tip(electrs, COINBASE_MATURITY + 1)
"""

TEMPLATES = {
    "chain-check": {
        "daemons": ["bitcoin-core"],
        "conftest": _CONFTEST_CORE,
        "body": _CHAIN_BODY,
        "run_flags": "",
    },
    "wallet-roundtrip": {
        "daemons": ["bitcoin-core"],
        "conftest": _CONFTEST_CORE,
        "body": _WALLET_BODY,
        "run_flags": "--wallet ",
    },
    "electrs": {
        "daemons": ["bitcoin-core", "electrs"],
        "conftest": _CONFTEST_ELECTRS,
        "body": _ELECTRS_BODY,
        "run_flags": "",
    },
}

DEFAULT_TEMPLATE = "chain-check"


def _render(template, filename, copyright_holders):
    tpl = TEMPLATES[template]
    header = _HEADER.format(
        year=datetime.now().year,
        copyright_holders=copyright_holders,
        daemons=", ".join(tpl["daemons"]),
        build_flags=" ".join("%s latest" % build_flag_for(d) for d in tpl["daemons"]),
        filename=filename,
        run_flags=tpl["run_flags"],
    )
    return header + "\n" + tpl["body"]


def _write(dest, content, force):
    if os.path.exists(dest) and not force:
        fail("%s already exists — use --force to overwrite", dest)
    with open(dest, "w") as handle:
        handle.write(content)
    LOG.info("scaffolded %s", dest)


def scaffold(
    paths,
    *,
    name=None,
    template=DEFAULT_TEMPLATE,
    copyright_holders="selfcustody",
    force=False,
):
    """Write an example integration test (and the ``conftest.py`` declaring its
    backends, if there is none yet) into ``<project>/tests/integration``"""
    if template not in TEMPLATES:
        fail(
            "unknown template '%s' — known: %s",
            template,
            ", ".join(sorted(TEMPLATES)),
        )
    tpl = TEMPLATES[template]

    name = re.sub(r"\W+", "_", name or tpl["daemons"][-1]).strip("_")
    if not name:
        fail("invalid test name — use letters, digits or underscores")
    filename = "test_%s.py" % name

    os.makedirs(paths.integration_dir, exist_ok=True)
    dest = os.path.join(paths.integration_dir, filename)
    if os.path.exists(dest) and not force:
        fail("%s already exists — use --force to overwrite", dest)

    conftest = os.path.join(paths.integration_dir, "conftest.py")
    if os.path.exists(conftest) and not force:
        LOG.warning(
            "%s already exists — kept as is; %s expects its fixtures",
            conftest,
            filename,
        )
    else:
        _write(conftest, tpl["conftest"], force)

    _write(dest, _render(template, filename, copyright_holders), force)
    return dest
