# The MIT License (MIT)
#
# Copyright (c) 2026 selfcustody
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Generated by ``bornal`

    target: bitcoin-core, floresta on regtest.

Build the daemon(s) and run this test with the bornal's ``pytest`` plugin::

    pytest --build-bitcoin latest --build-floresta latest tests/integration/test_floresta.py
"""

import pytest

from bornal.daemon import free_port
from bornal.node import IntegrationTest
from bornal.plugins.bitcoind import UNSPENDABLE_ADDRESS
from bornal.testing import (
    assert_block_count,
    assert_chain,
    generate_to_address,
    sync_blocks,
)


class FlorestaTest(IntegrationTest):
    """florestad never listens for p2p: it dials the bitcoind declared before it"""

    def set_test_params(self):
        p2p_port = free_port()
        self.add_backend("bitcoin-core", p2p_port=p2p_port)
        self.add_backend("floresta", connect="127.0.0.1:%d" % p2p_port)

    def run_test(self):
        self.log.info("Tests running")


@pytest.fixture(scope="module")
def test_factory(request):
    return FlorestaTest


@pytest.fixture
def alice(integration_test):
    return integration_test.backends[0]


@pytest.fixture
def florestad(integration_test):
    return integration_test.backends[1]


@pytest.fixture
def electrum(florestad):
    return florestad.daemon.make_electrum_client()


def test_000_genesis(alice, florestad):
    assert_chain(alice, "regtest")
    assert_chain(florestad, "regtest")
    assert_block_count(alice, 0)
    assert_block_count(florestad, 0)


def test_001_sync(alice, florestad):
    generate_to_address(alice, UNSPENDABLE_ADDRESS, 10)
    sync_blocks(alice, florestad)
    assert_block_count(florestad, 10)
    assert florestad.client.get_best_block_hash() == alice.client.call(
        "getbestblockhash"
    )


def test_002_peer(alice, florestad):
    peers = florestad.client.get_peer_info()
    assert len(peers) == 1
    assert peers[0]["address"] == "127.0.0.1:%d" % alice.daemon.p2p_port


def test_003_electrum(electrum):
    assert electrum.server_version()[0].startswith("Floresta")
    assert electrum.get_tip()["height"] == 10
    assert electrum.block_headers(0, 11)["count"] == 11
