# The MIT License (MIT)
#
# Copyright (c) 2026 selfcustody
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Generated by ``bornal`

    target: bitcoin-core, electrs on regtest.

Build the daemon(s) and run this test with the bornal's ``pytest`` plugin::

    pytest --build-bitcoin latest --build-electrs latest tests/integration/test_electrs.py
"""

from bornal.plugins.bitcoind import UNSPENDABLE_ADDRESS
from bornal.testing import (
    COINBASE_MATURITY,
    assert_block_count,
    assert_chain,
    assert_electrs_tip,
    connect_p2p,
    generate_to_address,
    sync_blocks,
)


def test_000_index(alice, bob, bob_electrs):
    connect_p2p(alice, bob)
    assert_chain(alice, "regtest")
    assert_chain(bob, "regtest")
    assert_block_count(alice, 0)
    assert_block_count(bob, 0)
    assert_electrs_tip(bob_electrs, 0)
    generate_to_address(alice, UNSPENDABLE_ADDRESS, COINBASE_MATURITY + 1)
    assert_block_count(alice, COINBASE_MATURITY + 1)
    sync_blocks(alice, bob)
    assert_block_count(bob, COINBASE_MATURITY + 1)
    assert_electrs_tip(bob_electrs, COINBASE_MATURITY + 1)
